CREATE DATABASE RELATIONSHIP;

USE RELATIONSHIP;

CREATE TABLE STDDETAILS(
STD_ID INT IDENTITY PRIMARY KEY,
STD_NAME VARCHAR(20),
STD_ADDRESS VARCHAR(50)
);

CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(20),
STD_ID INT FOREIGN KEY REFERENCES dbo.STDDETAILS(STD_ID)
);

CREATE TABLE SUBJECTS(
SUB_ID INT PRIMARY KEY,
SUB_NAME VARCHAR(20) NOT NULL,
DEPT_ID INT FOREIGN KEY REFERENCES dbo.DEPARTMENT(DEPT_ID) NULL
);

CREATE TABLE RESULTS(
GRADE VARCHAR(4),
SUB_ID INT REFERENCES dbo.SUBJECTS(SUB_ID)
);



